In [ ]:
'''
TUGAS1 DDP SI Rabu Siang

Buat Dictionary (Bobot Penilaian 20 Point):
p1 : nama=>Budi, produk=> TV, jumlah=>3
p2 : nama=>Ani, produk=> AC, jumlah=>4
p3 : nama=>Siti, produk=> Kulkas, jumlah=>2
p4 : nama=>Dewi, produk=> AC, jumlah=>5
p5 : nama=>Andi, produk=> Kulkas, jumlah=>7
p6 : nama=>Dedi, produk=> AC, jumlah=>1
p7 : nama=>Sri, produk=> TV, jumlah=>4

Semua pelanggan masukkan ke sebuah list dengan nama ar_pelanggan (Bobot Penilaian 5 Point)
Cetaklah Data Pembelian Pelanggan Menggunakan Nested Loop Dengan Data:
- Nama Pelanggan(Bobot Penilaian 5 Point)
- Produk Beli (Bobot Penilaian  5 Point)
- Jumlah Beli (Bobot Penilaian  10 Point)
- Harga Satuan: (Bobot Penilaian 20 Point)
  Gunakan kondisional if:
  (TV=>5 jt, AC=>6 jt, Kulkas=>7 jt)
- Harga Kotor => Jumlah Beli x Harga Satuan (Bobot Penilaian  10 Point)
- Diskon: (Bobot Penilaian 10 Point)
  Gunakan Tuple & List 
  Jika Beli Produk Kulkas minimal 3 pcs dapat diskon 20% dari harga kotor,
  Selain itu diskon hanya 5% dari harga kotor
- PPN => 11% x (Harga Kotor - Diskon) (Bobot Penilaian 10 Point)
- Harga Bayar => (Harga Kotor + PPN) - Diskon (Bobot Penilaian 5 Point)
'''

p1 = {'nama':"Samsul",
      'produk':'TV',
      'jumlah': 3}
p2 = {'nama':"Ani",
      'produk':'AC',
      'jumlah': 4}
p3 = {'nama':"Dewi",
      'produk':'kulkas',
      'jumlah': 2}
p4 = {'nama':"Siti",
      'produk':'AC',
      'jumlah': 5}
p5 = {'nama':"Tanto",
      'produk':'kulkas',
      'jumlah': 7}
p6 = {'nama':"Dedi",
      'produk':'AC',
      'jumlah': 1}
p7 = {'nama':"Sri",
      'produk':'TV',
      'jumlah': 4}
ar_pelanggan = [p1,p2,p3,p4,p5,p6,p7]

for pelanggan in ar_pelanggan:
  for m in pelanggan:
    # harga satuan
    if pelanggan['produk'] == 'TV':
      harga_satuan = 5000000

    elif pelanggan['produk'] == 'AC':
      harga_satuan = 6000000
      
    else :
      harga_satuan = 7000000
    
    # harga kotor
    harga_kotor = pelanggan['jumlah'] * harga_satuan

    #diskon
    if pelanggan['jumlah'] >= 3:
      diskon = 0.2 * harga_kotor

    else: 
      diskon = 0.05 * harga_kotor 
    
    #ppn
    ppn = 0.11 * (harga_kotor - diskon)

    #harga bayar
    harga_bayar = (harga_kotor + ppn) - diskon

  print('harga satuan\t:',harga_satuan,
        '\nharga kotor\t:',harga_kotor,
        '\ndiskon\t\t:',diskon,
        '\nppn\t\t:',ppn,
        '\nharga bayar\t:',harga_bayar,
        '\n-----------------------------')

harga satuan	: 5000000
harga kotor	: 15000000
diskon		: 3000000.0
ppn		: 1320000.0
harga bayar	: 13320000.0
-----------------------------
harga satuan	: 6000000
harga kotor	: 24000000
diskon		: 4800000.0
ppn		: 2112000.0
harga bayar	: 21312000.0
-----------------------------
harga satuan	: 7000000
harga kotor	: 14000000
diskon		: 700000.0
ppn		: 1463000.0
harga bayar	: 14763000.0
-----------------------------
harga satuan	: 6000000
harga kotor	: 30000000
diskon		: 6000000.0
ppn		: 2640000.0
harga bayar	: 26640000.0
-----------------------------
harga satuan	: 7000000
harga kotor	: 49000000
diskon		: 9800000.0
ppn		: 4312000.0
harga bayar	: 43512000.0
-----------------------------
harga satuan	: 6000000
harga kotor	: 6000000
diskon		: 300000.0
ppn		: 627000.0
harga bayar	: 6327000.0
-----------------------------
harga satuan	: 5000000
harga kotor	: 20000000
diskon		: 4000000.0
ppn		: 1760000.0
harga bayar	: 17760000.0
-----------------------------